import { addMonths } from "date-fns";
import { _TRANSACTION_TYPE, _TRANSACTION_FREQUENCY, _TRANSACTION_STATUS } from "@/constant";
import { TransactionType } from "@/features/transaction/transationType";

  
export const TRANSACTION_DATA: TransactionType[] = [
  {
    _id: "txn_1",
    userId: "user_1",
    title: "Freelance Payment",
    amount: 1200,
    type: _TRANSACTION_TYPE.INCOME,
    category: "Freelance",
    description: "",
    paymentMethod: "",
    date: new Date(2023, 5, 15).toISOString(),
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 15), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_2",
    userId: "user_1",
    date: new Date(2023, 5, 16).toISOString(),
    title: "Grocery Store",
    amount: 85.50,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Food",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 16), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_3",
    userId: "user_1",
    date: new Date(2023, 5, 17).toISOString(),
    title: "Electric Bill",
    amount: 75.20,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Utilities",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 17), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_4",
    userId: "user_1",
    date: new Date(2023, 5, 18).toISOString(),
    title: "Consulting Work",
    amount: 500,
    type: _TRANSACTION_TYPE.INCOME,
    category: "Services",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 18), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_5",
    userId: "user_1",
    date: new Date(2023, 5, 19).toISOString(),
    title: "Coffee Shop",
    amount: 4.75,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Food",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 19), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_6",
    userId: "user_1",
    date: new Date(2023, 5, 20).toISOString(),
    title: "Online Course",
    amount: 89.99,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Education",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 20), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_7",
    userId: "user_1",
    date: new Date(2023, 5, 21).toISOString(),
    title: "Rent Payment",
    amount: 950,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Housing",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 21), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_8",
    userId: "user_1",
    date: new Date(2023, 5, 22).toISOString(),
    title: "Stock Dividends",
    amount: 42.50,
    type: _TRANSACTION_TYPE.INCOME,
    category: "Investments",
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    nextRecurringDate: addMonths(new Date(2023, 5, 22), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_9",
    userId: "user_1",
    date: new Date(2023, 5, 23).toISOString(),
    title: "Gym Membership",
    amount: 35,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Health",
    recurringInterval: null,
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    nextRecurringDate: null,
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_10",
    userId: "user_1",
    date: new Date(2023, 5, 24).toISOString(),
    title: "Book Sale",
    amount: 28.40,
    type: _TRANSACTION_TYPE.INCOME,
    category: "Sales",
    recurringInterval: null,
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    nextRecurringDate: null,
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_11",
    userId: "user_1",
    date: new Date(2023, 5, 25).toISOString(),
    title: "Netflix Subscription",
    amount: 15.99,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Entertainment",
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    nextRecurringDate: addMonths(new Date(2023, 5, 25), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_12",
    userId: "user_1",
    date: new Date(2023, 5, 26).toISOString(),
    title: "Salary Deposit",
    amount: 3000,
    type: _TRANSACTION_TYPE.INCOME,
    category: "Salary",
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    nextRecurringDate: addMonths(new Date(2023, 5, 26), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "txn_13",
    userId: "user_1",
    date: new Date(2023, 5, 27).toISOString(),
    title: "Gym Membership",
    amount: 35,
    type: _TRANSACTION_TYPE.EXPENSE,
    category: "Health",
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    isRecurring: true,
    description: "",
    paymentMethod: "BANK_TRANSFER",
    lastProcessed: new Date().toISOString(),
    status: _TRANSACTION_STATUS.COMPLETED,
    nextRecurringDate: addMonths(new Date(2023, 5, 27), 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'txn_001',
    userId: 'user_123',
    title: 'Monthly Salary',
    type: _TRANSACTION_TYPE.INCOME,
    amount: 4500,
    description: 'May 2024 Salary',
    category: 'Salary',
    date: '2024-05-01',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    nextRecurringDate: '2024-06-01',
    lastProcessed: '2024-05-01',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'BANK_TRANSFER',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z'
  },
  {
    _id: 'txn_002',
    userId: 'user_123',
    title: 'Grocery Shopping',
    type: _TRANSACTION_TYPE.EXPENSE,
    amount: 120,
    description: 'Weekly grocery shopping',
    category: 'Food',
    date: '2024-05-02',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.WEEKLY,
    nextRecurringDate: '2024-05-09',
    lastProcessed: '2024-05-02',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'CASH',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-02T08:00:00Z'
  },
  {
    _id: 'txn_003',
    userId: 'user_123',
    title: 'Electricity Bill',
    type: _TRANSACTION_TYPE.EXPENSE,
    amount: 150,
    description: 'Monthly electricity bill',
    category: 'Utilities',
    date: '2024-05-03',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    nextRecurringDate: '2024-06-03',
    lastProcessed: '2024-05-03',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'BANK_TRANSFER',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-03T08:00:00Z'
  },
  {
    _id: 'txn_004',
    userId: 'user_123',
    title: 'Monthly Salary',
    type: _TRANSACTION_TYPE.INCOME,
    amount: 4500,
    description: 'May 2024 Salary',
    category: 'Salary',
    date: '2024-05-01',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    nextRecurringDate: '2024-06-01',
    lastProcessed: '2024-05-01',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'BANK_TRANSFER',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z'
  },
  {
    _id: 'txn_005',
    userId: 'user_123',
    title: 'Grocery Shopping',
    type: _TRANSACTION_TYPE.EXPENSE,
    amount: 120,
    description: 'Weekly grocery shopping',
    category: 'Food',
    date: '2024-05-02',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.WEEKLY,
    nextRecurringDate: '2024-05-09',
    lastProcessed: '2024-05-02',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'CASH',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-02T08:00:00Z'
  },
  {
    _id: 'txn_006',
    userId: 'user_123',
    title: 'Electricity Bill',
    type: _TRANSACTION_TYPE.EXPENSE,
    amount: 150,
    description: 'Monthly electricity bill',
    category: 'Utilities',
    date: '2024-05-03',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    nextRecurringDate: '2024-06-03',
    lastProcessed: '2024-05-03',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'BANK_TRANSFER',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-03T08:00:00Z'
  },
  {
    _id: 'txn_007',
    userId: 'user_123',
    title: 'Monthly Salary',
    type: _TRANSACTION_TYPE.INCOME,
    amount: 4500,
    description: 'May 2024 Salary',
    category: 'Salary',
    date: '2024-05-01',
    isRecurring: true,
    recurringInterval: _TRANSACTION_FREQUENCY.MONTHLY,
    nextRecurringDate: '2024-06-01',
    lastProcessed: '2024-05-01',
    status: _TRANSACTION_STATUS.COMPLETED,
    paymentMethod: 'BANK_TRANSFER',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z'
  },
];